### ISSUE TITLE
Why is password reset sender at `GET /password/reset` rather than `POST /password/reset`?

### ISSUE THREAD

**Issue by silasdavis** [keratin/authn-server#107]
I was surprised that we have:

```go
route.Get("/password/reset").
	SecuredWith(originSecurity).
	Handle(handlers.GetPasswordReset(app))
```

When I would have thought it would have been a `POST` since it certainly affects our state and kicks off a webhook sender with modest cost.

The webhook sender itself then performs a POST to the backend so we in effect have a POST behind a GET.

Is there a reason I am missing?

I wondered if it might be a PUT if we duplicated concurrent webhook requests but seems not.

**Comment by cainlevy** [comment]
Fair question!

I've historically chosen `GET` for this endpoint because sending an email doesn't feel like modifying state. It's like requesting the form to create a new resource.

Then I made the webhook sender perform a POST because I didn't want to transmit information in a query string. Small practicalities, there.

I realize this may not be a satisfying answer. At present, I think the choice is arguable and would need more persuasion to start on a breaking change to the API.

**Comment by cainlevy** [comment]
Happy to reconsider if this is causing issues.
