### ISSUE TITLE
Error Maintain: restore: Get: Open: cipher: message authentication failed

### ISSUE THREAD

**Issue by Kulak** [keratin/authn-server#125]
I am trying the application and run into the error:

    Maintain: restore: Get: Open: cipher: message authentication failed

there is no other context reported.

**Comment by cainlevy** [comment]
AuthN generates private keys regularly, and stashes encrypted versions into a persistent memory in case it needs to coordinate with another AuthN process (or with a future version).

This error happened while decrypting a previous key. The most likely culprit is a changing `SECRET_KEY_BASE`.

Please let me know if there's more to investigate here.

**Comment by drevets** [comment]
@cainlevy 

Hi! Due to the Heroku security incident, I'm (out of an abundance of caution) rotating environment variables. I updated the SECRET_KEY_BASE of our staging incidence and now our keratin-authn app is crashing. I do not know the previous value and now see that this may, in fact, be expected behavior. 

What can I do (if anything) to "reset" our app so it ingests the new SECRET_KEY_BASE value as legitimate? And what is the process (if any) for rotating the value of SECRET_KEY_BASE? 

Thanks!

**Comment by cainlevy** [comment]
If you're rotating the `SECRET_KEY_BASE` it could make sense to throw away all existing sessions by connecting to a new Redis database. I think you can accomplish this by changing your [REDIS_URL](https://pkg.go.dev/github.com/go-redis/redis/v8#ParseURL) with a new DB number (e.g. from `/0` to `/1`).

If this were a proactive event it may be worth investing in transition support with "old" and "new" key bases. In a reactive situation like this, I'm not sure if it's worth supporting the keys that are no longer trustworthy.

**Comment by cainlevy** [comment]
I reviewed the AuthN app to see what's in Redis and confirm that it's safe to discard: https://github.com/keratin/authn-server/blob/main/app/app.go

What I found, apart from session information that would be inaccessible without the old secret anyway, is the hyperloglog store of active users statistics.

Another way to rotate secrets might involve a bit of downtime. The encrypted keys in Redis are only retained for twice the ACCESS_TOKEN_TTL so I believe turning off AuthN for that long would mean it has nothing to decrypt when it starts up again. The default for that value is 1 hour.
