### ISSUE TITLE
[OAuth] Fosite

### ISSUE THREAD

**Issue by gregdhill** [keratin/authn-server#127]
To further elaborate on the second point in #124, I have decided to embed [fosite](https://github.com/ory/fosite) in our project (pericyte). This means that we can natively support the login / consent flow and can therefore act as a fully OIDC compliant microservice.

Before I consider submitting a PR, would this be something you would like in authn, or do you see it as the responsibility of the host app? I would probably argue for the latter in the case of hydra since it is itself a separate service which assumes certain security responsibilities, but integrating fosite directly would obviously allow for a tighter harness against keratin. For instance, hydra adopts its own notion of a user session but fosite would assume a smaller footprint therefore minimizing the potential attack surface in addition to leveraging many of keratin's best practices - such as key rotation.

**Comment by cainlevy** [comment]
Can you say more about how you would envision a stock AuthN service providing the UI bits of an OAuth 2.0 flow? Where does the HTML for `/login` and `/consent` (to borrow Hydra's terms) come from?

**Comment by gregdhill** [comment]
That's still the responsibility of the client, in the same way `/login` currently is. We would however require additional logic in the front-end to handle the setting of scopes - which I would imagine could be bundled into login.

For example, this is how I would envision a basic OAuth2 flow:

1. Client -> Issuer (keratin [fosite] - `/oauth2/auth`)
  * Not Authenticated: Issuer -> Redirect (`config.AppLoginURL`)
    * Login - POST `/session`
    * Redirect to 1 w/ `scopes`
  * Authenticated: Issuer -> Client (`code`)
2. Client -> Issuer (`/oauth2/token`)
3. Issuer -> Client (`access_token`, `refresh_code`, `id_token`, etc.)

**Comment by silasdavis** [comment]
Hi @cainlevy - @gregdhill and I work together and have spoken about this a bit.

I think you have a valid concern here for sure. The scope could become quite a bit of Hydra. We would need to come up with a principle for bounding that scope at least. 

Having had the same concern with respect of picking apart the security stance and functionality of Hydra, we have done it, and it's ended up cleaner than I expected. What we have found is that by combining elements of the particular (rather standard auth code flow) that we need from Fosite and coupling with AuthN as we do we were able to cut a fair bit of complexity around redirects (we can just service login and consent handlers internally), as well as communicating duplicated configuration and running too services.

It seems like the Hydra approach of having no batteries included with respect for user management might make sense if you already have user management, but is a bit of a pain otherwise. It also aims to provide the full gamut of OIDC flows, where AuthN could probably carve out a smaller amount of functionality.

Having said all this I can see the problem of feature creep. We are building integrations that definitely seem like they are more general than our use case - we'd like to push them upstream somewhere, but this main not be the place. It might be worth us coming back to this once we have matured our implementation, and see if we have an argument to make about a limited OIDC provider scope based on fosite.

**Comment by cainlevy** [comment]
I think it makes a lot of sense for you to build the one auth code flow that you need and to skip redirects in your blended service.

I'm not optimistic that it would work for AuthN as a standalone microservice though. The scope boundary (one auth code flow) is harder to maintain, and redirects to login and consent pages must still be handled properly.

The everlasting discussion around service architecture (and code organization in general!) is size and scope. When is a service too small, or too big? Is it better to go all in on a monolith, break out composable pieces that require more glue to put together, or find a middle ground?

AuthN intends to provide a general solution to a universal problem in a way that fits equally well alongside a monolith or a SoA architecture. This means it favors a composition strategy where developers are free to make choices about what else they need in their system. That may sometimes mean more glue, but it always means more empowerment.

Thanks for pushing me to clarify and articulate this philosophy.

So what does it mean for your work? 

> We are building integrations that definitely seem like they are more general than our use case

Sounds like you've done the work of composing together a few smaller building blocks into something larger. That's great! I'm sure you're not the only team that wants to make the same choices. If you decide to share it, it would be an excellent addition to the OSS community.

I'm going to look at writing a guide to recommend Hydra (or similar) for anyone who wants their application to be an OIDC provider. I haven't done it myself so it will be hand-wavey. I'd certainly appreciate feedback and revisions from you (or anyone reading this later) who has more first-hand experience.
