### ISSUE TITLE
Notification Signing

### ISSUE THREAD

**Issue by AlexCuse** [keratin/authn-server#207]
I’d like to have a signing facility for the notifications sent on password resets / reset notifications.  A simple HMAC of the body would do for our needs but wanted to ask here before looking too close at a PR if there’s anything else we should look to support.

Not something I’ve used but I see a url configured for passwordless logins wonder if it could maybe leverage same.

**Comment by AlexCuse** [comment]
Shared secret and HMAC (`APP_SIGNING_SECRET` / `APP_SIGNING_KEY`) are probably the low hanging fruit here.  Will look to start on those when I get time.

**Comment by cainlevy** [comment]
HMAC is nice and simple, but will require a shared secret. The alternative would be a public/private key pair setup like access tokens rely on. It's tempting to reuse the existing key pair, but I haven't thought through how key rotation might affect it.

Previously, I had assumed that people would use a notification URL with basic auth. SSL is basically a must because of the sensitive nature of the reset tokens that get passed across, and it should also protect the basic auth. I suppose what's missing, compared to HMAC, is some proof that the payload hasn't been tampered. Still ... SSL is a must.

**Comment by AlexCuse** [comment]
Yep we use basic auth + SSL right now and it’s fine.  We should have a private network endpoint for these probably but such is life.  Would look to add this in addition.

I like that HMAC is relatively simple.  But the key reuse is an interesting idea too, it’s an easy way for apps using authn-go client already if nothing else, implementation in other languages not terribly hard but have to manage your own key requests etc… .  Can see how I get on w first few and look at what it would take to add from there.  Option 3 might actually be lightest integration lift for us right now.
