### ISSUE TITLE
JWT support

### ISSUE THREAD

**Issue by jalberto** [keratin/authn-server#27]
JWT support will be nice to integrate AuthN with kong and similar systems

**Comment by cainlevy** [comment]
AuthN does currently issue JWT tokens. I'm inclined to believe that this works out of the box. If it does not, it's a fixable bug.

The one catch is that Kong appears to depend on uploaded verification keys. This means configuring AuthN with a [static RSA key](https://github.com/keratin/authn-server/blob/master/docs/config.md#rsa_private_key), rather than relying on AuthN to automatically generate and rotate.
