### ISSUE TITLE
Dockerfile does not run migrate by default

### ISSUE THREAD

**Issue by ernsheong** [keratin/authn-server#57]
If one uses docker-compose from the get-go, this could be a gotcha. Should migrations generally be part of runtime or separate?

**Comment by cainlevy** [comment]
I suppose that I defaulted to making them separate because they are not zero cost, even if they are fast. But you're right to observe that making them separate allows a dev to forget.

I'd like to hear a bit more about your experience. Do you think this is a gotcha primarily in development, or also in production? Would your instinct to bundle the migrations into startup be different in each environment?

It'd be nice to have an example docker-compose setup or guide for folks getting started. That might include a `command` override to ensure that migrations run in development. It wouldn't really help with production, though, where folks with Dockerized deployments are more likely to use ECS, Kubernetes, etc.

**Comment by ernsheong** [comment]
Simply putting `command: ./authn migrate && ./authn server` doesn't work. Migration does, starting server doesn't. Maybe `command: ./authn migrate &; ./authn server;` might work

**Comment by cainlevy** [comment]
@ernsheong try `command: sh -c "./authn migrate && ./authn server"`. i believe that's a docker limitation.

**Comment by Mohammed90** [comment]
@cainlevy I've just used `command: sh -c "./authn migrate && echo 'starting server, migrations finished' && ./authn server"` in the `docker-compose.yml` with `DATABASE_URL=sqlite3://:memory:?mode=memory&cache=shared` and it works perfectly. I didn't think doing the two commands with `&&` would solve it 😄
