### ISSUE TITLE
Option to turn off Origin checking?

### ISSUE THREAD

**Issue by ernsheong** [keratin/authn-server#58]
I find `Origin` checking somewhat clunky. 

Consider these use cases:
1. Communicate backend to backend using AuthN public API. In this case the other backend needs to set Origin header manually (and redundantly).
2. The Origin header is only set automatically by the browser in the case of CORS. It is entirely possible to host the API in a separate path, e.g. `/api` while hosting the web app from the same domain. In this case the Origin header is not set by the browser?
3. When using Postman it is easy to spoof origin checking, so I don't think it gives much value in terms of security defence. Also it is a bit of a gotcha for newcomers just testing things out.

Hence I think there should be an option to turn off Origin checking completely.

**Comment by cainlevy** [comment]
Origin is only checked to prevent CSRF attacks. What other mechanism would you propose to replace it?

Some thoughts on these use cases:

1) 
    This setup is some service acting as a proxy between the client and AuthN, yes? It's an unsupported architecture because one of the primary design constraints for AuthN was ensuring that raw passwords would never pass through a backend that might inspect or log parameters. Think of passwords like credit card numbers, and AuthN like a secrets vault.

    Nonetheless, if someone wanted to deploy that setup, they would currently also need to forward Cookie headers back and forth. I think it's okay to expect that they will also manage Origin. At that point they're really taking a number of security decisions into their own hands anyway.

2) I'm using AuthN in a production scenario that does exactly what you describe. Our API shares the same domain and is distinguished by path. Origin checking hasn't been a problem, and I'm not certain why! My best clue is this [MDN article](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin):

    > It is sent with CORS requests, as well as with POST requests.

3) Postman is a development tool, yes? The CSRF security risk is in production, but I'd be reluctant to make it optional in development only because that difference in behavior seems like a whole other gotcha.

I'd welcome your thoughts on any of this! I'm interested in making things simpler, especially for newcomers, but there are certain security characteristics that AuthN needs to maintain.

**Comment by ernsheong** [comment]
@cainlevy thanks for the detailed response!

Looks like Point 2 is moot. POST requests do send Origin, my bad.

Yeah I think the fact that Cookies are still used in the architecture, is somewhat of a dealbreaker for me. I had preferred a pure (short-lived) access and (long-lived) refresh token based approach _without_ the use of cookies, and using the Authentication header to send access tokens back. Perhaps this needs to be documented, and is it also not clear which token is the access/refresh token, the one in the cookie or in the JSON.

I'm not expecting changes. Just stirring up some discussion.

**Comment by cainlevy** [comment]
I would like an alternative to cookies for native apps, but haven't had the opportunity to personally work on a native app yet and don't want to go beyond my expertise.

> I had preferred a pure (short-lived) access and (long-lived) refresh token based approach without the use of cookies, and using the Authentication header to send access tokens back.

OAuth specifically recommends against returning refresh tokens to public clients. That's why they created an implicit flow. The problem is that public clients are less secure, and refresh tokens are more dangerous when compromised.

AuthN uses a cookie for the refresh token because it can take advantage of browser settings to make the cookie unavailable to JavaScript (guards against XSS) and only sent over HTTPS (guards against SSLStrip).

Further, AuthN assumes that it _can_ use cookies because it assumes that public endpoints are receiving traffic directly from a client and not from an application's backend. This takes the responsibility for secure password handling and login away from your application backend, and is the reason why AuthN (as an authentication _service_) can be more secure than a typical authentication _plugin_.
