### ISSUE TITLE
How to remove user from authn?

### ISSUE THREAD

**Issue by qqqqqz** [keratin/authn-server#84]
For example i have created the user on register from frontend- when i do- i first create in auth from client-> then send the info with account_id to server and create user in app database with its info- but > what if the server side fails- i should some how remove the user from auth. Is there things for such cases?

**Comment by cainlevy** [comment]
Excellent question. I've taken two approaches.

1) Cleanup - in the backend, detect when a user has an AuthN account and no matching user record. This is an incomplete signup, so use the AuthN admin API in your backend integration (Ruby? Go?) to delete the account.

2) Recover - detect the same incomplete situation but instead offer a form to finish signing up.

The second approach is nice if you have plans to integrate OAuth in the future, because you can reuse the same "finish creating your account" form when a user returns from Google/Facebook/Twitter.
