### ISSUE TITLE
Add support for Multifactor Authentication (MFA / TFA)

### ISSUE THREAD

**Issue by silasdavis** [keratin/authn-server#92]
Is this something you would consider/have considered? It seems to me like it would be an appropriate features to situate in authn-server and It's something I need.

For example, by integrating: https://github.com/pquerna/otp 

I would be willing to work on this, if you have some initial guidance then I could give a draft design / implementation proposal.

**Comment by cainlevy** [comment]
@silasdavis Yes! I agree that MFA is in scope and TOTP is a good place to start.

Eventually I'd like to also support delivered codes (email or SMS), so it'd be ideal if the implementation considered those to minimize migrations and API changes later.

Recovery codes should be in scope. They should not live in plaintext, though. Might be best to treat them like passwords.

I'm uncertain about an admin API for disabling MFA. On the one hand, it could improve the ability to support account recovery. On the other hand, it could be nice for MFA to offer protection against abuse of the admin API. Let's defer this decision, since that's the more secure position.

What's your recommendation for remembering a secret while waiting for the user to validate it?

AuthN should eventually be able to support both optional and required MFA. I suspect that starting with optional MFA is the best (and most desirable) MVP, since required MFA will add complexity to onboarding new and existing accounts. Thoughts?

When you draft a proposal, please look for opportunities to review and merge the feature in discrete steps. I don't expect this to be a trivial change!

**Comment by silasdavis** [comment]
>Eventually I'd like to also support delivered codes (email or SMS)
A bit like in #94 this makes me wonder about more general ways for authn to 'push back' on certain hooks.

> What's your recommendation for remembering a secret while waiting for the user to validate it?
Encrypt and store in Redis I suppose...

I think admin-disabling MFA should probably be an option, probably also need to facilitate a compulsory MFA login - for which the application would need to be able to distinguish a logged in user without MFA from a logged in user with MFA and require them to enable MFA. We might be able to defer this but probably worth having a vague idea.

It will probably be a few weeks before I am ready to get to this, but should have a better feel for the codebase by then

**Comment by cainlevy** [comment]
> We might be able to defer [compulsory MFA logins] but probably worth having a vague idea.

Yeah, it's worth peeking ahead. For example, if MFA is implemented as a failure code during login then it'd be easy to reply with failure codes that tell the client what to do next (collect MFA _or_ onboard MFA).

But perhaps the complexity in compulsory MFA really lives in the onboarding process, since the onboarding APIs would need to work with half-authenticated users.

**Comment by silasdavis** [comment]
When you say onboarding APIs, to what are you referring, just to be clear?

**Comment by cainlevy** [comment]
The APIs necessary to add MFA to an account

**Comment by cainlevy** [comment]
@thenhawke thanks for taking the lead on this! i'll respond further in your pull request when i've had a chance to study it.
