### ISSUE TITLE
Using authn-server as a library?

### ISSUE THREAD

**Issue by silasdavis** [keratin/authn-server#94]
I note that the intended mode of operation for authn-server is for it to be run as an isolated service exposed to your front end, e.g. https://github.com/keratin/authn-server/issues/79.

I was initially sold on the principle of isolation for the authentication service but I have an number of requirements that make me wonder if I would be better off integrating authn-server as a library into a Go service of my own. In particular I need to:

1. To synchronize with another database (a blockchain) on user signup (and possible on other account changes)
2. Expose a consent app to Ory Hydra to act as an OpenID connect provider
3. Ideally talk to other services over GRPC (I know that is in hand)

I think I could work around all of these with various separate services, but it feels like I may end up doing a lot of busywork to write a Go app to deal with these. 1 might be fundamentally better solved by dealing with things atomically in a single request scope.

In any case I will be building an account management service for multiple backend services (privacy settings, email sending, organisation admin etc) to handle this across our platform so I'm going to end up with two quite tightly coupled services to operate, where my account service ends up proxying at least the signup call to authn-server.

My question is where do you stand on using authn as a library? Is it something that totally subverts the design you had in mind, or is it just that I would need to be prepared for breakages in internal APIs? They way things are structured now seems open to extension - I think I could live with them not being stable.

Perhaps there is scope for some kind of synchronisation/callback interface that maintains the boundary but allows for some tightly coupled logic to run with authentication/signup. It might work a bit like an extension to `WebhookSender`, perhaps implemented as a GRPC stream, or if building in Go could work by running authn-server within a Go wrapper and subscribing to events.

**Comment by cainlevy** [comment]
Let me turn this back to you: what's the value proposition of authn-server as a library?

I've seen a lot of authentication libraries. I've seen a fair number of third-party authentication services. My approach to authn-server has been to explore the middle ground, gaining isolation without giving over account management to another brand.

This means I've made choices that optimize authn-server for a particular setup. If you decided to seek a different setup, then I'd be curious to know what you valued in authn vs some other authentication library.

> Perhaps there is scope for some kind of synchronisation/callback interface that maintains the boundary but allows for some tightly coupled logic to run with authentication/signup.

I find this direction more interesting. The boundary that authn-server creates has worked fairly well for me (after dealing with atomic signup).

One concept I've been thinking about for a 2.0 is creating a more mature webhook system that posts any number of events or trigger to a single configurable URL. The reason I haven't gone further is that I can imagine a number of setups on the other side, from message brokers to background workers. Each host app will have a difference preference.

Maybe there's something lightweight that authn-server can do to integrate with different host apps, like choose a webhook strategy based on the configuration URL. I feel like REST is simply the lowest common denominator, so that's my default thinking.

**Comment by silasdavis** [comment]
> Let me turn this back to you: what's the value proposition of authn-server as a library?

Perhaps this is a given, but I don't want to write my own:
- HTTP interface/CORS support etc
- Session store
- Password store
- Token issuance/validation
- Lots of tests

I will/may want to write:
- Tightly coupled signup logic
- Directly spawn (i.e. from Go service) workers for email, analytics, checking quotas (_maybe_)
- Some consent-level/authorisation logic
- Handle non-user-agent (i.e browser) signup/login - e.g. machine service accounts over gRPC

There is also some advantage in terms of moving quickly to owning the 'main.go' when a simple code change makes the service fit your infrastructure better - minor things like config, more significant things like bypassing the session store if using authn logic for an OIDC login and concent flow (whenthe OIDC server handles sessions.

In particular I like the way authn-server is structured and the code itself. I think some of this comes from the fact it's primary customer is itself as a microservice.

>I've seen a lot of authentication libraries

The nearest competitor I have seen that provides the full gamut of password/session is https://github.com/volatiletech/authboss - interested to know if you think there are others.

>This means I've made choices that optimize authn-server for a particular setup. 

Done in the right way exposing a 'library face' does not need to be antagonistic to being a good service. Libraries with a 'main.go' can benefit from be their own customer first but also getting some design pressure from other library users. I still think authn-server the service should be your primary motivator. Pure libraries have a tendency to become a medley of features without a coherent design, this was my initial feeling about AuthBoss (which may be unfair, though I also don't like its implicit configuration by import side-effects). I'm biased by my own main project having a library component as well as being a fully-fledged service - I think it can work well - the service keeps you focussed and the library helps you separate concerns.

>One concept I've been thinking about for a 2.0 is creating a more mature webhook system 

It seems like a prerequisite to such a webhook system is an internal interface for pushing events around. If someone (like me) is using you as a library, then I would want to help build that same interface. I'd just happen to be using it from the same Go process. To expose it from the service you would add the transport level dispatcher on top of it, but a library user could help provide input earlier as you incrementally implement it.

One approach to this would be to spin out an 'authn' library. Whilst this is appealing conceptually, I wouldn't recommend it until it is much clearer what it would be and there is enough development velocity to justify the hassle of two repos.

**Comment by cainlevy** [comment]
I follow. Thanks for the perspective! I hadn't considered that AuthN as a library might still go further than the normal package due to its HTTP implementation.

I'm happy to accept improvements that make AuthN easier to use as a library whenever those improvements are at least net neutral for AuthN as a microservice. We can see where it goes from there!

Final caution for anyone reading this (now or in the future): if you go this route, please remember that you're bringing more logic and churn inside the authentication security perimeter. That means more potential points of vulnerability.
